import subprocess
import os
import hashlib
import pytest
import pickle

from compare_files import compare_files

# Define your CLI commands
commands = [
    {'cmd': 'python train.py --config induction.yaml'}
]

REFERENCE_DIR = 'tests/references'
OUTPUT_DIR = 'tests/output'


def get_file_name(cmd):
    hash_object = hashlib.md5(cmd.encode())
    return hash_object.hexdigest()


# Helper function to run the command
def run_command(command):
    result = subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    # if result.returncode != 0:
    #     raise RuntimeError(f"Command failed: {command}\nError: {result.stderr}")
    print(result.returncode)
    print(result.stdout)
    print(result.stderr)


# Function to get all files in a directory
def get_all_files_in_directory(directory):
    file_paths = []
    for root, _, files in os.walk(directory):
        for file in files:
            file_paths.append(os.path.join(root, file))
    return file_paths


@pytest.mark.parametrize('cmd_data', commands)
def test_generate_references(cmd_data):
    cmd = cmd_data['cmd']
    file_name = get_file_name(cmd)
    file_path = os.path.join(REFERENCE_DIR, f"{file_name}")
    run_command(f"{cmd} --file {file_path}")

    # make sure the references were generated
    # file_path does not contain the extension so make sure there are files with the same name but different extensions
    assert os.path.exists(f"{file_path}.pkl")
    assert os.path.exists(f"{file_path}.pth")


# Test function for each command
@pytest.mark.parametrize('cmd_data', commands)
def test_cli_command(cmd_data):
    # Run the command
    cmd = cmd_data['cmd']
    file_name = get_file_name(cmd)
    file_path = os.path.join(OUTPUT_DIR, f"{file_name}")
    run_command(f"{cmd} --file {file_path}")

    # Get the list of files generated by the command
    generated_files = get_all_files_in_directory(OUTPUT_DIR)

    # Loop through each generated file and compare it to its reference
    for generated_file in generated_files:
        # Get the corresponding reference file path
        reference_file = os.path.join(REFERENCE_DIR, os.path.relpath(generated_file, OUTPUT_DIR))

        # Check if the reference file exists
        if os.path.exists(reference_file):
            # Compare the generated file with the reference file
            assert compare_files(generated_file, reference_file,
                                 method="hash"), f"File {generated_file} does not match the reference {reference_file}"
        else:
            # If no reference exists, throw an error and report missing reference
            pytest.fail(
                f"No reference found for generated file '{generated_file}'. Expected reference at: {reference_file}")
