seed: 1919
# wandb:
#   key: ""
#   entity: ""
#   project: ""
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
train:
  num_epochs: 30
  batch_size: 64
  lr: 0.0002
  wd: 0.01
model:
  layer: "mamba"
  num_blocks: 6
  input_dim: 1
  output_dim: 10
  hidden_dim: 256
  state_dim: 64
  conv_dim: 4
  expansion: 2
  dropout: 0.0
  glu: True
  norm: "layer"
  dual: False
  prenorm: False
  pooling: "mean"