seed: 1919
# wandb:
#   key: ""
#   entity: ""
#   project: ""
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
train:
  num_epochs: 30
  batch_size: 32
  lr: 0.0001
  wd: 0.01
model:
  layer: "hawk"
  num_blocks: 6
  input_dim: 1
  output_dim: 10
  hidden_dim: 256
  kernel_size: 4
  expansion: 1
  gmlp_expansion: 1.5
  dropout: 0.0
  init: "uniform"
  dual: False
  pooling: "mean"